[package]
name = "anything"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
bevy = { version = "*", features = [] }          #Remove dynamic when building release
bevy-inspector-egui = "0.17.0"
